cc_test(
    name = "test_all",
    srcs = [
        "camera_spec.cpp",
        "player_spec.cpp",
        "utils_spec.cpp",
        "video_spec.cpp",
    ],
    deps = [
        "//mylib",
        "@googletest//:gtest_main",
    ],
)
