cc_library(
    name = "mylib",
    srcs = [
        "camera.cpp",
        "player.cpp",
        "utils.cpp",
        "video.cpp",
    ],
    hdrs = [
        "camera.h",
        "player.h",
        "utils.h",
        "video.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@opencv//:opencv-lib",
    ],
)
